version: '3'

name: uexplorer

volumes:
  cassandra-volume:

services:
  cassandra:
    image: cassandra:4.0.6
    container_name: cassandra
    restart: "on-failure"
    networks:
      - backend
    ports:
      - 127.0.0.1:9044:9042
    oom_kill_disable: true
    volumes:
      - cassandra-volume:/var/lib/cassandra
    environment:
      - HEAP_NEWSIZE=${CASSANDRA_HEAP_NEWSIZE:-1G}
      - MAX_HEAP_SIZE=${CASSANDRA_MAX_HEAP_SIZE:-4G}
      - CASSANDRA_CLUSTER_NAME=ergo-cluster
    healthcheck:
      test: cqlsh -e "describe keyspaces" || exit 1
      interval: 5s
      timeout: 5s
      start_period: 31s
      retries: 6
  cassandra-init:
    image: cassandra:4.0.6
    container_name: cassandra-init
    restart: "no"
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - ./cassandra.cql:/cassandra.cql
    environment:
      - CQLSH_HOST=cassandra
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh -f /cassandra.cql"
  stargate:
    image: stargateio/stargate-4_0:v1.0.65
    container_name: stargate
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - backend
    ports:
      # cql
      - 127.0.0.1:9045:9042
      # graphql
      - 127.0.0.1:8085:8080
      # auth
      - 127.0.0.1:8081:8081
      # REST
      - 127.0.0.1:8082:8082
      # health
      - 127.0.0.1:8084:8084
      # grpc
      - 127.0.0.1:8090:8090
    environment:
      - SEED=cassandra
      - JAVA_OPTS="-Xmx1G"
      - CLUSTER_NAME=ergo-cluster
      - CLUSTER_VERSION=4.0
      - RACK_NAME=rack1
      - DATACENTER_NAME=datacenter1
      - ENABLE_AUTH=false
    healthcheck:
      test: curl --fail http://127.0.0.1:8082 || exit 1
      interval: 3s
      timeout: 1s
      start_period: 12s
      retries: 4
  uexplorer:
    image: pragmaxim/uexplorer:latest
    container_name: uexplorer
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-init:
        condition: service_completed_successfully
    networks:
      - backend
    volumes:
      - ./chain-indexer.conf:/uexplorer/conf/chain-indexer.conf
    environment:
      # override in case you run your own Ergo node deployment
      - LOCAL_ERGO_NODE_HOST=host.docker.internal
      - LOCAL_ERGO_NODE_PORT=9053
      # override in case you run your own Cassandra deployment
      - CASSANDRA_SEED_HOST=cassandra
      - CASSANDRA_SEED_PORT=9042
networks:
  backend: