version: '2'

services:
  cassandra:
    image: cassandra:4.0.6
    container_name: cassandra
    networks:
      - backend
    ports:
      - 9044:9042
    oom_kill_disable: true
    volumes:
      - ${PWD}/cassandra.cql:/tmp/cassandra.cql
      - ${PWD}/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - /var/lib/cassandra:/var/lib/cassandra
    environment:
      - HEAP_NEWSIZE=${CASSANDRA_HEAP_NEWSIZE}
      - MAX_HEAP_SIZE=${CASSANDRA_MAX_HEAP_SIZE}
      - CASSANDRA_CLUSTER_NAME=ergo-cluster
  stargate:
    image: stargateio/stargate-4_0:v1.0.65
    container_name: stargate
    depends_on:
      - cassandra
    networks:
      - backend
    ports:
      # cql
      - 9045:9042
      # graphql
      - 8085:8080
      # auth
      - 8081:8081
      # REST
      - 8082:8082
      # health
      - 8084:8084
      # grpc
      - 8090:8090
    environment:
      - JAVA_OPTS="-Xmx1536M"
      - CLUSTER_NAME=ergo-cluster
      - CLUSTER_VERSION=4.0
      - SEED=cassandra
      - RACK_NAME=rack1
      - DATACENTER_NAME=datacenter1
      - ENABLE_AUTH=false
networks:
  backend: