name: Build and Push Docker image

on:
  push:
    tags: ["*"]

jobs:
  build_and_push:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Docker Metadata action
        uses: docker/metadata-action@v3.5.0
        id: meta
        with:
          images: pragmaxim/uexplorer-chain-indexer
      -
        name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
